language: node_js

node_js:
- node

env:
- BUILD_MODE=release

before_script:
- make deps

script:
- npm run flow status
- make

deploy:
  provider: script

  script:
  - ./scripts/release.sh

  on:
    tags: true
